apiVersion: batch/v1
kind: Job
metadata:
  name: throw-dice-job
spec:
  completions: 3
  # parallelism: 3 # run containers in parallel until completion
  activeDeadlineSeconds: 1800 #The maximum duration the job can run
  backoffLimit: 6 # The number of retries for a job
  ttlSecondsAfterFinished: 100 #cleanup the job after completion
  template:
   spec:
      containers:
      -  image: kodekloud/throw-dice
         name: throw-dice
      restartPolicy: Never
