apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: atsea-ingress
  namespace: atsea
spec:
  rules:
   - http:
      paths:
      - path: /shop
        backend:
          serviceName: appserver
          servicePort: 8080
