# ServiceAccountsto can be used to assign cluster roles,
# or the ability to use particular HTTP verbs.

apiVersion: v1
kind: ServiceAccount
metadata:
 name: secret-access
---
# Now we'll grant access to view Secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-access-cr
  rules:
    - apiGroups:
      - ""
      resources:
        - secrets
      verbs:
        - get
        - list
---
# The role binding to combine the secret-access service account and role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-rb
  subjects:
  - kind: ServiceAccount
name: secret-access-sa
roleRef:
  kind: ClusterRole
  name: secret-access-cr
apiGroup: rbac.authorization.k8s.io
---
# Next specify serviceAccountName: secret-access-sa in Pod definition
