apiVersion: v1
kind: Pod
metadata:
  labels:
    run: time-check
  name: time-check
  namespace: time-frequency
spec:
  containers:
  # run command
  - args:
    - bin/sh
    - -c
    - while true; do date; sleep $TIME_FREQ;done > /opt/time/time-check.log    
    # or to use command like
    # command: ["bin/sh", "-c", "while true; do date; sleep $TIME_FREQ;done > /opt/time/time-check.log"]
    
    image: busybox
    name: time-check
    resources: {}
    env:
     - name: TIME_FREQ
       valueFrom:
        configMapKeyRef:
          name: time-config
          key: TIME_FREQ
    volumeMounts: 
    - name: myvolume
      mountPath: /opt/time
  volumes:
  - name: myvolume
    emptyDir: {}
