# One can check in UI that app is connecting to mysql successfully
# before and after adding the secrets
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-pod
  name: webapp-pod
  namespace: default
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    imagePullPolicy: Always
    name: webapp
    envFrom:
    - secretRef:
        name: db-secret
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-pod
  name: webapp-pod
  namespace: default
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    imagePullPolicy: Always
    name: webapp
    env:
     - name: DB_Host
       valueFrom:
         secretKeyRef:
          name: db-secret
          key: DB_Host
     - name: DB_User
       valueFrom:
         secretKeyRef:
          name: db-secret
          key: DB_User
     - name: DB_Password
       valueFrom:
         secretKeyRef:
           name: db-secret
           key: DB_Password
