apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
