apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  volumeMode: Filesystem
  capacity:
      storage: 1Gi
  hostPath:
    path: '/opt/volume/nginx'
