apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    app: demo-voting-app
    name: result-app-pod

spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerport: 80
