apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    app: demo-voting-app
    name: voting-app-pod
    
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerport: 80
