apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: demo-voting-app
    name: redis-svc

spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: demo-voting-app
    name: redis-pod
