apiVersion: apps/v1
kind: Depployment
metadata:
  name: voting-app-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
        app: demo-voting-app
        name: voting-app-pod
  template:
    # pod
    metadata:
      name: voting-app-pod
      labels:
        app: demo-voting-app
        name: voting-app-pod

    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
